
services:
  biseccion:
    build:
      context: .
      dockerfile: Dockerfile.biseccion  
    ports:
      - "5000:5000"  
    environment:
      - SERVICE_NAME=biseccion

  punto_fijo:
    build:
      context: .
      dockerfile: Dockerfile.punto_fijo  
    ports:
      - "5001:5000"  
    environment:
      - SERVICE_NAME=punto_fijo

  newton:
    build:
      context: .
      dockerfile: Dockerfile.newton  
    ports:
      - "5002:5000"  
    environment:
      - SERVICE_NAME=newton

  secante: 
    build:
      context: .
      dockerfile: Dockerfile.secante  
    ports:
      - "5003:5000"
    environment:
      - SERVICE_NAME=secante


  jacobi: 
    build:
      context: .
      dockerfile: Dockerfile.jacobi  
    ports:
      - "5005:5000"  
    environment:
      - SERVICE_NAME=jacobi


  gauss: 
    build:
      context: .
      dockerfile: Dockerfile.gauss  
    ports:
      - "5006:5000"  
    environment:
      - SERVICE_NAME=gauss   

